apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A valid .Values.name entry required!" .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ required "A valid .Values.name entry required!" .Values.name }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ required "A valid .Values.clusterIssuerName entry required!" .Values.clusterIssuerName }}
  dnsNames: {{ required "A valid .Values.dnsNames entry required!" .Values.dnsNames }}
  {{ if .Values.annotations }}
  secretTemplate:
    annotations:
      {{- toYaml .Values.annotations | nindent 6 }}
  {{ end }}
