apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: {{ .Release.Namespace | quote }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "A valid .Values.email entry required!" .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer
    solvers:
      - http01:
          ingress:
            class: nginx
