apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: {{ .Release.Namespace | quote }}
data:
  access-token: {{ required "A valid .Values.token entry required!" .Values.token | b64enc }}
