apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-do-cluster-issuer-staging
  namespace: {{ .Release.Namespace | quote }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ required "A valid .Values.email entry required!" .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-do-cluster-issuer-staging
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
