apiVersion: v1
kind: Secret
metadata:
  name: {{ required "A valid .Values.name entry required!" .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
  {{ if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{ end }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
